apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80          # This is the port exposed on the service
      targetPort: 4499  # This is the port your app listens on
  type: NodePort        # Changed from LoadBalancer to NodePort
