name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t anushakotla1205/wisecow-app:latest .

      - name: Push Docker Image
        run: |
          docker push anushakotla1205/wisecow-app:latest

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CA_CERT }}" | base64 --decode > $HOME/.kube/ca.crt
          echo "${{ secrets.KUBE_CLIENT_CERT }}" | base64 --decode > $HOME/.kube/client.crt
          echo "${{ secrets.KUBE_CLIENT_KEY }}" | base64 --decode > $HOME/.kube/client.key
          echo "apiVersion: v1" > $HOME/.kube/config
          echo "clusters:" >> $HOME/.kube/config
          echo "  - cluster:" >> $HOME/.kube/config
          echo "      certificate-authority: $HOME/.kube/ca.crt" >> $HOME/.kube/config
          echo "      server: https://127.0.0.1:51801" >> $HOME/.kube/config
          echo "    name: minikube" >> $HOME/.kube/config
          echo "contexts:" >> $HOME/.kube/config
          echo "  - context:" >> $HOME/.kube/config
          echo "      cluster: minikube" >> $HOME/.kube/config
          echo "      namespace: default" >> $HOME/.kube/config
          echo "      user: minikube" >> $HOME/.kube/config
          echo "    name: minikube" >> $HOME/.kube/config
          echo "current-context: minikube" >> $HOME/.kube/config
          echo "kind: Config" >> $HOME/.kube/config
          echo "preferences: {}" >> $HOME/.kube/config
          echo "users:" >> $HOME/.kube/config
          echo "  - name: minikube" >> $HOME/.kube/config
          echo "    user:" >> $HOME/.kube/config
          echo "      client-certificate: $HOME/.kube/client.crt" >> $HOME/.kube/config
          echo "      client-key: $HOME/.kube/client.key" >> $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
