name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t anushakotla1205/wisecow-app:latest .

      - name: Push Docker Image
        run: |
          docker push anushakotla1205/wisecow-app:latest

      - name: Install Minikube
        run: |
          sudo curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo chmod +x minikube
          sudo mv minikube /usr/local/bin/

      - name: Start Minikube
        run: |
          minikube start --driver=docker

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CA_CERT }}" | base64 --decode > ~/.kube/ca.crt
          echo "${{ secrets.KUBE_CLIENT_CERT }}" | base64 --decode > ~/.kube/client.crt
          echo "${{ secrets.KUBE_CLIENT_KEY }}" | base64 --decode > ~/.kube/client.key
          minikube update-context

      - name: Deploy to Minikube
        run: |
          kubectl apply -f ./deployment.yaml
          kubectl apply -f ./service.yaml