name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different
      - main  # Change this if your main branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t your-dockerhub-username/wisecow-app:latest .

      - name: Push Docker Image
        run: |
          docker push your-dockerhub-username/wisecow-app:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: anushakotla1205/wisecow-app:latest  # Change this to your Docker Hub username
