name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Using the latest version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Using the latest version

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Using the latest version
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t anushakotla1205/wisecow-app:latest .

      - name: Push Docker Image
        run: |
          docker push anushakotla1205/wisecow-app:latest

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CA_CERT }}" | base64 --decode > ~/.minikube/ca.crt
          echo "${{ secrets.KUBE_CLIENT_CERT }}" | base64 --decode > ~/.minikube/client.crt
          echo "${{ secrets.KUBE_CLIENT_KEY }}" | base64 --decode > ~/.minikube/client.key
          cat > ~/.kube/config <<- 'EOF'
          apiVersion: v1
          clusters:
            - cluster:
                certificate-authority: ~/.kube/ca.crt
                server: https://127.0.0.1:59628  # Minikube server URL from your kubeconfig
              name: minikube
          contexts:
            - context:
                cluster: minikube
                namespace: default
                user: minikube
              name: minikube
          current-context: minikube
          kind: Config
          preferences: {}
          users:
            - name: minikube
              user:
                client-certificate: ~/.minikube/client.crt
                client-key: ~/.minikube/client.key
          EOF

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f C:/Users/91990/wisecow/deployment.yaml
          kubectl apply -f C:/Users/91990/wisecow/service.yaml